FROM alpine:3.14

EXPOSE 8080
# dependencies
RUN apk update
RUN apk add python3
RUN apk add --update py-pip

ADD api /
WORKDIR /

RUN pip3 install -r requirements.txt


CMD ["python3", "-m" , "api.py"]